In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [15]:
np.random.seed(42)

N = 500
K = 3
D = 2

X = np.zeros((N, D))
y = np.zeros((N, 1), dtype=int)

centers = [(-2,0),(2,0),(0,2)]
pts = N // K

start = 0
for k in range(K):
    if k == K - 1:
        end = N
        num_points = end - start
    else:
        end = start + pts
        num_points = pts

    cx, cy = centers[k]
    X[start:end] = np.random.randn(num_points, D) * 0.5 + np.array([cx, cy])
    y[start:end] = k

    start = end


In [17]:
Y = np.zeros((N, K))
for i in range(N):
    Y[i, y[i,0]] = 1


In [18]:
class NN(object):

    def __init__(self):
        self.inputLayerNeurons  = 2
        self.hiddenLayer1Neurons = 10
        self.hiddenLayer2Neurons = 8
        self.outputLayerNeurons = 3

        self.W_HI1 = np.random.randn(self.inputLayerNeurons,
                                     self.hiddenLayer1Neurons)

        self.W_I1I2 = np.random.randn(self.hiddenLayer1Neurons,
                                      self.hiddenLayer2Neurons)

        self.W_OH  = np.random.randn(self.hiddenLayer2Neurons,
                                     self.outputLayerNeurons)

        self.lr = 0.01

    def sigmoid(self, x, der=False):
        s = 1 / (1 + np.exp(-x))
        if der:
            return s * (1 - s)
        return s

    def softmax(self, x):
        x = x - np.max(x, axis=1, keepdims=True)
        ex = np.exp(x)
        return ex / np.sum(ex, axis=1, keepdims=True)

    def feedForward(self, x):
        self.z1 = np.dot(x, self.W_HI1)
        self.a1 = self.sigmoid(self.z1)

        self.z2 = np.dot(self.a1, self.W_I1I2)
        self.a2 = self.sigmoid(self.z2)

        self.z3 = np.dot(self.a2, self.W_OH)
        pred = self.softmax(self.z3)
        return pred

    def backprop(self, x, y, pred):
        m = x.shape[0]

        output_delta = (pred - y)

        hidden2_error = np.dot(output_delta, self.W_OH.T)
        hidden2_delta = hidden2_error * self.sigmoid(self.z2, der=True)

        hidden1_error = np.dot(hidden2_delta, self.W_I1I2.T)
        hidden1_delta = hidden1_error * self.sigmoid(self.z1, der=True)

        self.W_OH  -= self.lr * np.dot(self.a2.T, output_delta)
        self.W_I1I2 -= self.lr * np.dot(self.a1.T, hidden2_delta)
        self.W_HI1 -= self.lr * np.dot(x.T, hidden1_delta)

    def train(self, x, y):
        pred = self.feedForward(x)
        self.backprop(x, y, pred)


In [19]:
obj = NN()

for i in range(2000):
    obj.train(X, Y)

print("Training complete.")


Training complete.


In [26]:
preds = obj.feedForward(X)
print(preds[:33])



[[0.999873 0.000039 0.000088]
 [0.999751 0.000025 0.000225]
 [0.999874 0.00003  0.000096]
 [0.999678 0.000052 0.000269]
 [0.999854 0.000023 0.000123]
 [0.999877 0.000031 0.000092]
 [0.999837 0.000138 0.000025]
 [0.999867 0.000023 0.000109]
 [0.999858 0.000022 0.00012 ]
 [0.999891 0.000041 0.000068]
 [0.999844 0.000088 0.000069]
 [0.999881 0.000076 0.000042]
 [0.999864 0.000025 0.000111]
 [0.999857 0.000022 0.000122]
 [0.999872 0.000028 0.0001  ]
 [0.999827 0.00002  0.000153]
 [0.999889 0.000053 0.000058]
 [0.999847 0.00012  0.000032]
 [0.999835 0.00014  0.000024]
 [0.999859 0.000022 0.00012 ]
 [0.999859 0.000037 0.000103]
 [0.999876 0.000032 0.000091]
 [0.999872 0.000025 0.000102]
 [0.999843 0.000022 0.000136]
 [0.999842 0.000131 0.000027]
 [0.99988  0.000041 0.000079]
 [0.999853 0.000022 0.000124]
 [0.999778 0.000032 0.00019 ]
 [0.999871 0.000026 0.000103]
 [0.999828 0.000025 0.000147]
 [0.999871 0.000027 0.000102]
 [0.999886 0.000033 0.000081]
 [0.999746 0.000027 0.000227]]
